server:
  port: 9000
  write_timeout: 15
  read_timeout: 15
  idle_timeout: 60
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  db_name: "todoList"
redis:
  host: "localhost"
  port: 6379
  password: "redis"
