// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AccountUpdateRequest account update request
//
// swagger:model AccountUpdateRequest
type AccountUpdateRequest struct {

	// account id
	// Required: true
	// Minimum: 1
	AccountID int64 `json:"account_id"`

	// name
	// Required: true
	// Min Length: 1
	Name string `json:"name"`
}

// Validate validates this account update request
func (m *AccountUpdateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountUpdateRequest) validateAccountID(formats strfmt.Registry) error {

	if err := validate.Required("account_id", "body", int64(m.AccountID)); err != nil {
		return err
	}

	if err := validate.MinimumInt("account_id", "body", m.AccountID, 1, false); err != nil {
		return err
	}

	return nil
}

func (m *AccountUpdateRequest) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", m.Name, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this account update request based on context it is used
func (m *AccountUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccountUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountUpdateRequest) UnmarshalBinary(b []byte) error {
	var res AccountUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
