// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AccountDeleteRequest account delete request
//
// swagger:model AccountDeleteRequest
type AccountDeleteRequest struct {

	// account id
	// Required: true
	// Minimum: 1
	AccountID int64 `json:"account_id"`
}

// Validate validates this account delete request
func (m *AccountDeleteRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountDeleteRequest) validateAccountID(formats strfmt.Registry) error {

	if err := validate.Required("account_id", "body", int64(m.AccountID)); err != nil {
		return err
	}

	if err := validate.MinimumInt("account_id", "body", m.AccountID, 1, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this account delete request based on context it is used
func (m *AccountDeleteRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccountDeleteRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountDeleteRequest) UnmarshalBinary(b []byte) error {
	var res AccountDeleteRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
