// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetClientPaymentsRequest get client payments request
//
// swagger:model GetClientPaymentsRequest
type GetClientPaymentsRequest struct {

	// account id
	AccountID int64 `json:"account_id,omitempty"`
}

// Validate validates this get client payments request
func (m *GetClientPaymentsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get client payments request based on context it is used
func (m *GetClientPaymentsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetClientPaymentsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetClientPaymentsRequest) UnmarshalBinary(b []byte) error {
	var res GetClientPaymentsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
