// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Payment payment
//
// swagger:model Payment
type Payment struct {

	// account id
	// Required: true
	// Minimum: 1
	AccountID int64 `json:"account_id"`

	// reason
	// Min Length: 1
	Reason string `json:"reason,omitempty"`

	// sum
	Sum float64 `json:"sum,omitempty"`
}

// Validate validates this payment
func (m *Payment) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReason(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Payment) validateAccountID(formats strfmt.Registry) error {

	if err := validate.Required("account_id", "body", int64(m.AccountID)); err != nil {
		return err
	}

	if err := validate.MinimumInt("account_id", "body", m.AccountID, 1, false); err != nil {
		return err
	}

	return nil
}

func (m *Payment) validateReason(formats strfmt.Registry) error {
	if swag.IsZero(m.Reason) { // not required
		return nil
	}

	if err := validate.MinLength("reason", "body", m.Reason, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this payment based on context it is used
func (m *Payment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Payment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Payment) UnmarshalBinary(b []byte) error {
	var res Payment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
