// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReportDebtorsRequest report debtors request
//
// swagger:model ReportDebtorsRequest
type ReportDebtorsRequest struct {

	// account ids
	AccountIds []int64 `json:"account_ids"`
}

// Validate validates this report debtors request
func (m *ReportDebtorsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this report debtors request based on context it is used
func (m *ReportDebtorsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReportDebtorsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReportDebtorsRequest) UnmarshalBinary(b []byte) error {
	var res ReportDebtorsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
